"""Spherical intensity-relief recipe contracts."""

from .field import (
    DirectionalSamples,
    SeamDiagnostics,
    SphericalScalarField,
    build_spherical_scalar_field,
    directions_to_lambert_square,
    interpolate_sample_ledger,
    lambert_square_to_directions,
    sample_spherical_field,
)
from .recipes import (
    ReliefFDMContext,
    ReliefGeometrySpec,
    ReliefGlobeRecipe,
    ReliefMappingSpec,
    ReliefSourceExpectation,
    SphericalFilterSpec,
    load_relief_globe_recipe,
)
from .mapping import (
    MappedDirectionalSamples,
    MappedSphericalField,
    ReliefGeometry,
    SphericalFilterDiagnostics,
    build_relief_geometry,
    filter_spherical_values,
    map_source_field,
    sample_mapped_field,
)
from .topology import IcosphereTopology, build_icosphere
from .mesh import (
    FIELD_ARRAY_ORDER,
    ReliefFieldArtifact,
    ReliefMeshValidation,
    relief_field_npz_bytes,
    relief_stl_bytes,
    validate_relief_mesh,
    write_relief_preview,
)

__all__ = [
    "DirectionalSamples",
    "IcosphereTopology",
    "MappedDirectionalSamples",
    "MappedSphericalField",
    "ReliefFDMContext",
    "ReliefFieldArtifact",
    "ReliefGeometrySpec",
    "ReliefGlobeRecipe",
    "ReliefMappingSpec",
    "ReliefGeometry",
    "ReliefMeshValidation",
    "ReliefSourceExpectation",
    "SeamDiagnostics",
    "SphericalScalarField",
    "SphericalFilterSpec",
    "SphericalFilterDiagnostics",
    "FIELD_ARRAY_ORDER",
    "build_relief_geometry",
    "build_spherical_scalar_field",
    "build_icosphere",
    "directions_to_lambert_square",
    "filter_spherical_values",
    "interpolate_sample_ledger",
    "lambert_square_to_directions",
    "load_relief_globe_recipe",
    "map_source_field",
    "relief_field_npz_bytes",
    "relief_stl_bytes",
    "sample_mapped_field",
    "sample_spherical_field",
    "validate_relief_mesh",
    "write_relief_preview",
]
